### ISSUE TITLE
Only first .bin file imported

### ISSUE THREAD

**Issue by gomestai** [karikera/vscode-nwjs-debug#13]
I tried extension with nw.js 0.25.4 and 0.23.3. In both of versions only first .bin file imported, 2nd and 3rd just ignred. Code works perfect with sublime text 3. 

> nw.Window.get().evalNWBin(null, 'selector.bin');
> console.log("here1");
> nw.Window.get().evalNWBin(null, 'gui.bin');
> console.log("here2");
> nw.Window.get().evalNWBin(null, 'splash.bin');
> console.log("here3");
> 

all logs are printed in console, also first bin has `console.log` command and it works too, gui.bin and splash.bin are not imported and `console.log()` commands that they have not printing.

**Comment by karikera** [comment]
oh.. sorry about late reply
It looks like old version bug of NWjs, 
did you checked launch.json? if nwjsVersion is set it always launch that version

or isn't it NWjs itself problem? I'm just vscode extension developer..
