### ISSUE TITLE
Publish x86 binaries on 64bit system?

### ISSUE THREAD

**Issue by SLdragon** [karikera/vscode-nwjs-debug#15]
How to config nwjs.publish.json to publish x86 binaries on 64bit system?

Here is my config:

{
  "version": "1.0.0",
  "package": {},
  "html": [
    "index.html"
  ],
  "nwjsVersion": "0.14.7",
  "files": [],
  "exclude": []
}

Each time i run publish, it will automatically download and publish x64 binaries.

**Comment by karikera** [comment]
oh.. sorry about late.. 
You can write like "0.14.7(ia32)"
but it will show as warning ..

**Comment by SLdragon** [comment]
@karikera Thanks a lot, I will try it!
