### ISSUE TITLE
Published App root?

### ISSUE THREAD

**Issue by Spown** [karikera/vscode-nwjs-debug#17]
When I develop my app ``nw.__dirname`` is the path of my project's root, but when I run the published app - it turns into something like ``%APPDATA%\Local\Temp\nw12112_17666``. So, if I want some persistent data to be saved in the app root, like settings - it becomes problematic.

It would be nice to have a publishing option, that doesn't involve creating a zipped package, and that runs directly in the app folder. Just a plain simple dumping of nw.js and project data (that which is defined through ``files`` and ``exclude``) into one folder.

It also would be faster since there is no extraction time (which can be substantial). And no unnessessery HDD grind or SSD wear.

Thank you.

**Comment by karikera** [comment]
Thanks for advice!
I added `zip` option in nwjs.publish.json and it will use unzipped publish default!
