### ISSUE TITLE
launch trouble

### ISSUE THREAD

**Issue by DrYSG** [karikera/vscode-nwjs-debug#2]
I can provide more info about versions, code, etc. But this was an attempt to launch a very minimal debug session.

Cannot connect to runtime process, timeout after 10000 ms - (reason: Can't find a target that matches: chrome-extension://*/index.html. Available pages: ["chrome-extension://blmaelfcjbmcgkegnjbibdjbdiljjcnc/_generated_background_page.html"]).

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch NWJS",
            "type": "nwjs",
            "request": "launch",
            "webRoot": "${workspaceRoot}"
        },
        {
            "name": "Attach to Chrome",
            "type": "nwjs",
            "request": "attach",
            "port": 9222,
            "webRoot": "${workspaceRoot}"
        }
    ]
}
```

**Comment by karikera** [comment]
Debugger will launch nwjs
and after few second will attach to  "chrome-extension://*/${package.json/main}"
If it was not founded in 10000 ms,  will terminated (by redirect immediatly or something)

I don't know why your app have not any page without _generated_background_page.html
Can i see other things?

English is not my mother tongue; please excuse any errors on my part.

**Comment by DrYSG** [comment]
I really like what you are doing. And will try to help you in any way possible. But it would be good if you tell me exactly what you need in terms of info.

I am running on Win7 (64 bit). 
Visual Code: 1.8.1
Node: 6.5.0 
NW.JS version: 0.19.3

I don't know about  your debugger, but
This task.json file starts the program with no problems:

```
{
    "version": "0.1.0",
    "command": "cmd",
    "args": [
        "/c"
    ],
    "isShellCommand": true,
    "showOutput": "always",
    "suppressTaskName": true,
    "tasks": [
        {
            "taskName": "nw",
            "args": [
                "nw ."
            ]
        },
        {
            "taskName": "nw-remote",
            "args": [
                "nw --remote-debugging-port=9222 ."
            ]
        }
    ]
}
```

**Comment by DrYSG** [comment]
index.html

```
<!DOCTYPE html>
<html>

<head>
  <title>Test Package</title>
  <script src="./node_modules/jquery/dist/jquery.js"></script>
  <script src="main.js"></script>
</head>
<body style="width: 100%; height: 100%;">
<p>'Right click' to show context menu.</p>
</body>

</html>
```
---------

main.js

```
$(document).ready(start);

function start() {
    var os = require('os');
    var nwJSVersion = process.versions['node-webkit'];
    alert('You are running on ' + os.platform() + " nw.js version: " + nwJSVersion);
}
```

------

package.json
```
{
  "version": "0.1",
  "name": "index",
  "main": "index.html",
  "dependencies": {
    "jquery": "^3.1.1"
  }
}
```

**Comment by karikera** [comment]
this extension install nwjs to "%USERPROFILE%\.nwjs\nwjs-sdk-v0.14.7-win-ia32" and use it
maybe it was corrupted?...    or not supported version?...

maybe can fix it by replacing it

I will someday support installing other version...

**Comment by DrYSG** [comment]
My NWJS is installed at:

C:\Users\ysg4206\.nwjs\nwjs-sdk-v0.14.7-win-ia32

**Comment by karikera** [comment]
that task seems to run nwjs in the working directory..
is it wrong?...

It simply run like this command line and rest is almost like chrome debugger
![image](https://cloud.githubusercontent.com/assets/6016498/21838604/4d6d1d24-d816-11e6-982a-bda6a24749f7.png)
I can't understand how it went wrong...

**Comment by DrYSG** [comment]
I added the path to the nw.exe to the $PATH variable.

**Comment by DrYSG** [comment]
My machine has some performance issues. I was able to get the debuger to launch the app. But it ignored the breakpoint I set in on line 5 of main.js. Suggestions? (all I get is the alert pop-up).

**Comment by karikera** [comment]
chrome debugger will attach little later after launch,
you can debug load script by restart debugger(Ctrl+Shift+F5)

**Comment by DrYSG** [comment]
Excellent. It is now working. We should add the CTRL+SHIFT+F5 to the ReadME, as well as a way to increase the timeout, since others may run into the same issue.

**Comment by karikera** [comment]
Oh, Thanks for advice!
