### ISSUE TITLE
cannot debug when chrome already running

### ISSUE THREAD

**Issue by ahdung** [karikera/vscode-nwjs-debug#20]
OS: windows server 2008 R2 x64 with SP1
vscode: 1.24.1 x64
Debugger for NWjs: 1.0.16
NWjs: 0.14.7(ia32)-sdk
Chrome: 66.0.3359.139 x64

If chrome already running, press F5 will get this error:
![_20180620122101](https://user-images.githubusercontent.com/12094247/41637065-70db94d2-7484-11e8-9df7-fe9657b44e4d.png)

The message mean **Can not connect to process, will timeout after 10000ms**, if close chrome, no problem. Please help.

**Comment by npk48** [comment]
不清楚是什么导致的 但是有个workaround, 设置不同的端口就行了
launch.json里
{
            "type": "nwjs",
            "request": "attach",
            "name": "Attach to NWjs",
            "preLaunchTask": "launch app",
            "port": 9233,
            "webRoot": "${workspaceFolder}"
        }

task.json里
{
            "label": "launch app",
            "type": "shell",
            "command": "./runtime_debug/nw . --remote-debugging-port=9233",
            "options": {
                "cwd": "./"
            },
            "group": "build",
            "problemMatcher": []
        }

**Comment by ahdung** [comment]
@npk48 9223已经是错开的了，你的方法是attach，变化比较大，估计是别的地方起作用，我下次折腾时试试，感谢帮助。

**Comment by karikera** [comment]
@npk48 Thanks for your help too! :D

**Comment by karikera** [comment]
"--remote-debugging-port=9233" is not needed
it's already pushed by debugger!
