### ISSUE TITLE
Launches NodeWebkit application twice.

### ISSUE THREAD

**Issue by simpert** [karikera/vscode-nwjs-debug#21]
I am using the nwjs debugger with the following VS Code launch.json configuration:
``` json
{
        "type": "nwjs",
        "request": "launch",
        "name": "Launch NWjs",
        "nwjsVersion": "0.21.5",
        "webRoot": "${workspaceFolder}",
        "sourceMaps": true,
        "port": 8083,
        "env":
        {
            "GMXTESTID": 0
        },
        "runtimeArgs": [
            "",
            "--load-extension=${env:LOCALAPPDATA}\\Google\\Chrome\\User Data\\Default\\Extensions\\fmkadmapgofadopljbjfkapdkoienihi\\3.2.4_0"
            //"--load-extension=${env:LOCALAPPDATA}\\Google\\Chrome\\User Data\\Default\\Extensions\\fmkadmapgofadopljbjfkapdkoienihi\\3.2.3_0"
        ]
        //,"preLaunchTask": "Build"
    }
``` 
I am using VS Code v1.25.1
![2018-07-27](https://user-images.githubusercontent.com/2422222/43332942-d77bc95e-9186-11e8-922d-285584c3ce7e.png)

I have an nwjs application that I am debugging. The launch results in a success debugging session, however, my application is being launched twice. I cannot figure out what is causing this.

My app has a standard package.json with a main that points to a index.html. The html loads a webpack bundle at the bottom of the markup via a script tag and my bundle's entry point is a jquery loaded function where I load my main apps react component.

I believe when launching my app, something is causeing a process to start it up then causing a separate process to start up.

I do not know if this is related to the VS Code extension or not but something is definitely starting my app twice. I can write to console in script tag at bottom of html markup and this is displayed in VS Code debug Console twice. As is logs written in jquery ready function and my main app components constructors.

I am not sure what logs I can check for issues or where they are placed but if reuqired I will post any help with this problem that I can.

**Comment by simpert** [comment]
Sorry about the mix-up where I state I am working with an Electron application. It is a NW.JS version 0.21.5 application.

**Comment by karikera** [comment]
oh..
this extension reload page after debugger attached  ...  
so..  script will run twice...   

I will add option to ignore it in "launch.json"

I couldn't find better way to debug the script that instantly started..
