### ISSUE TITLE
Where does a project get published to?

### ISSUE THREAD

**Issue by toyssamurai** [karikera/vscode-nwjs-debug#22]
I ran NWjs Publish and the output said:

Convert html...
Compile js...
Copy files...
Generate exe...
Complete

But the "publish" directory is nowhere to be found? Where does it get published to? It will be helpful if the output message writes out the location of the publish directory.

**Comment by karikera** [comment]
Thanks for suggestion!
It published to "[project directory]/publish"
I will add message to notify that!
