### ISSUE TITLE
Electron

### ISSUE THREAD

**Issue by DrYSG** [karikera/vscode-nwjs-debug#3]
This is a great tool, and you are the first to do it. 

Any chance that you can do the same for Electron? (my project is moving from NW.JS to Electron).

**Comment by karikera** [comment]
Oh, Thank you for your interest. but maybe I can't support Electron
Sorry about that,

![mythingking](https://cloud.githubusercontent.com/assets/6016498/22121768/9409ec86-dec8-11e6-8593-1ae9dcd5b83b.png)

**Comment by DrYSG** [comment]
Not sorry myself. I switched to Electron, and I don't mind doing the MainProcess debuging in VSCODE, and the RenderProcess in Chrome. Since this lets me use the React and Redux extensions to the Chrome Debugger. I would miss them.

I would love to figure out how to export breakpoints in client side code from VSCODE to the Chrome debug tools. So that I can have them persistent.

**Comment by karikera** [comment]
I do not know the details.

I cloned from [Debugger for Chrome](https://github.com/Microsoft/vscode-chrome-debug)
And just convert typescript to javascript and did this
![whatamidid](https://cloud.githubusercontent.com/assets/6016498/22144236/5d5e55d2-df40-11e6-96a7-9b7e4f7e916f.png)

I know just few sequence
1. Launch chromeDebug.js with nodejs from vscode
![image](https://cloud.githubusercontent.com/assets/6016498/22145610/77df204e-df45-11e6-8d73-50d5b3f16a30.png)
2. chromeDebug.js use chromeDebugAdapter.js
![image](https://cloud.githubusercontent.com/assets/6016498/22145561/44817b66-df45-11e6-9504-41d0ca7b07a4.png)
3. chromeDebugAdapter.js run chrome(NWjs) with debug option and attach to it
![image](https://cloud.githubusercontent.com/assets/6016498/22145732/f651f3f2-df45-11e6-8982-5e33dd7a06ac.png)
![image](https://cloud.githubusercontent.com/assets/6016498/22145774/1134d4e6-df46-11e6-9e3c-a884af36f4ab.png)

4. It works :D

I could not explain well, but I hope it helps..

**Comment by DrYSG** [comment]
Actually, I do understand. And I think you should be congratulated.
