### ISSUE TITLE
Could you give more details?

### ISSUE THREAD

**Issue by Julyyq** [karikera/vscode-nwjs-debug#4]
I just followed your instructions, but not working as expect.

![screenshot 2017-02-27 15 20 54](https://cloud.githubusercontent.com/assets/2620575/23352141/6c03aa1e-fd00-11e6-8ab9-1da74624ad8d.png)

VSCode: 1.9.1

**Comment by karikera** [comment]
oh . . . 
"NWjs Install" command updated to can have various version...
I will change that screen shot..

**Comment by Julyyq** [comment]
@karikera I run `nwjs install` but nothing happened.

**Comment by karikera** [comment]
Oh.. thanks for report, 
It had first using problem,  
I fixed it 0.0.19 update
