### ISSUE TITLE
need update to new vscode debugger

### ISSUE THREAD

**Issue by jonlepage** [karikera/vscode-nwjs-debug#46]
Sup, this plugin need update to the new vscode debugger.
related to this discutions.
https://github.com/microsoft/vscode/issues/121611#issuecomment-822577893

thanks guys.

**Comment by AndyMagwayer** [comment]
In order to start a debug session, first select the configuration named Launch Program using the Configuration dropdown in the Run and Debug view. Once you have your launch configuration set, start your debug session with F5.

**Comment by jonlepage** [comment]
it fixed since few years thanks
