### ISSUE TITLE
Cannot connect to runtime process, timeout after 10000ms

### ISSUE THREAD

**Issue by vanekj** [karikera/vscode-nwjs-debug#5]
Hello,

I have a problem with debug that has stopped working for me.

When I start the debug, my app will launch like normally and after some time (10000ms?) it exits with this message:

`Cannot connect to runtime process, timeout after 10000ms - (reason: Got a response from the target app, but no target pages found).`

Could anyone help me please? I will post anything needed 🙂 

Thank you!

**Comment by Julyyq** [comment]
+1

**Comment by karikera** [comment]
Oh!, Thanks for report
I fix it at 1.0.2 update

**Comment by vanekj** [comment]
@karikera Working with 1.0.2, thank you! 🙂
