### ISSUE TITLE
Cannot run NWjs Install

### ISSUE THREAD

**Issue by cgoo85** [karikera/vscode-nwjs-debug#6]
Hi, I'm trying to install a version of the nwjs library in Visual Studio Code and when I run the first command in the command palette (nwjs install) the extension tries to recover the diferent versions but never shows me anything. It is always loading but no extra info is reported.

Any help?

Thank you

**Comment by karikera** [comment]
Thanks for bug report!
I fixed bug of displaying error in 1.0.6   (and some os name bug)
I'm not sure what is going on,,

**Comment by cgoo85** [comment]
I have try it just now and I get this error:

{"key":"1","value":{"_creator":null,"_nextState":null,"_state":{"name":"error","done":null,"then":null},"_value":{"name":"FetchError","message":"request to http://dl.nwjs.io/ failed, reason: connect ETIMEDOUT 34.206.150.92:80","type":"system","errno":"ETIMEDOUT","code":"ETIMEDOUT"},"_listeners":null,"_isException":false,"_errorId":3}}

Any idea?

**Comment by karikera** [comment]
oh, this extension download nwjs from "http://dl.nwjs.io/"
seem to cannot connect that site.

You can launch own NWjs by runtimeExecutable options (It is bugged but fixed it in 1.0.7 update)
![image](https://cloud.githubusercontent.com/assets/6016498/26051785/37e82b62-399e-11e7-8dd8-69845c19d633.png)
I hope this will help you
