### ISSUE TITLE
Unable to "nwjs install" on linux

### ISSUE THREAD

**Issue by ScriptKi77y** [karikera/vscode-nwjs-debug#7]
Using Ubuntu 16.04, I try to run the command "nwjs install" but the app tries to download 
>GET http://dl.nwjs.io/v0.23.0-beta1/nwjs-v0.23.0-beta1-undefined-x64.zip
>undefined

it's not detecting the operating system platform correctly and tries to install something that doesn't exist.

Edit: apparently you can fix the problem by editing the os.js file in the extension source and make also detect linux and then just install it as normal, then in your launch.json add the field "runtimeExecutable": "/home/user_name/.nwjs/nwjs-sdk-v0.22.3-linux-x64/nw" where user_name is your user name and change the nwjs version accordingly.

**Comment by karikera** [comment]
thanks for bug report!
I fixed os name bug in 1.0.6 update.

But i'm not tested in linux, i have not linux :(
I hope to fixed it

**Comment by ScriptKi77y** [comment]
Just tested your 1.0.7 release on Windows 10 and Ubuntu 16.04.
Everything seems to work as expected, it downloads NWJS versions correctly, installs,, attaches and debugs as expected.

Thank you!
