### ISSUE TITLE
Unable to remove nwjs version

### ISSUE THREAD

**Issue by vanekj** [karikera/vscode-nwjs-debug#8]
Hello there,

I have ran into issue when I am unable to remove installed nwjs version.
I am working with VSCode 1.12.2 on OSX 10.12.4

![vscode-console-remove](https://cloud.githubusercontent.com/assets/18655248/26200526/cf67af94-3bce-11e7-9b31-0b56d8beacc5.png)

Thank you for help!

**Comment by karikera** [comment]
Sorry for late
I cannot understand what is wrong..
Did you remove NWjs when you opened it?

I will update to use fs-extra instead of shelljs for use different remove function
i hope it works for you

You can remove NWjs directly, this extension do not record any other information.
