### ISSUE TITLE
Conflict of package.json schema

### ISSUE THREAD

**Issue by kimushu** [karikera/vscode-nwjs-debug#9]
Hello. Thanks for your nice extension.

I found that the [schema definition of this extension](https://github.com/karikera/vscode-nwjs-debug/blob/master/schema/package.schema.json) conflicts with [VSCode's definition](http://json.schemastore.org/package) (This is referenced from [here](https://github.com/Microsoft/vscode/blob/master/extensions/javascript/package.json#L99)).
For example, "keywords" property is incorrectly defined as a string. But the correct definition of "keywords" is **array of** string.
So I see errors even if package.json is fine.
![schema-error](https://cloud.githubusercontent.com/assets/1642194/26364317/de453f78-401e-11e7-9927-61f185bb73f8.png)

VSCode automatically merges multiple schema definitions.
So I think vscode-nwjs-debug should have only definitions for *NW.js specific* properties.
How do you think?

Thanks,

**Comment by karikera** [comment]
Oh..  Thanks for report
I will remove basic npm specific properties in 1.0.8 update.

**Comment by kimushu** [comment]
Great. Thanks!
